### ISSUE TITLE
Possible to add a detach method?

### ISSUE THREAD

**Issue by sommerper** [mostafaqanbaryan/zellij-attach-plugin#2]
Hi and thanks a bunch for making this!

I have been using it for a while and I realized that sometimes, when in a session, I needed to create a new session before switching to it. So what I would first need to do is detach from the current session and then create a new one.

Could also be that it's a job for a completely new plugin. But as far as I can see it should be possible within a plugin https://github.com/zellij-org/zellij/discussions/2448#discussioncomment-7803560

I would look into myself but I'm clueless when it comes to rust.

**Comment by datsfilipe** [comment]
Hey, @sommerper, I had the same problem you have now.

The thing is that the plugin relies on zellij layouts, so what you're missing is a default layout for your session. After you've created the default layout, the plugin will switch and create the session without problems.

See more about creating layouts here: https://zellij.dev/documentation/layouts.

**Comment by mostafaqanbaryan** [comment]
Hi @sommerper and thank you!

You could do something like this as well:

https://github.com/mostafaqanbaryan/dotfiles/blob/7f2e3ee6207d6049a6b78acd79949257b12aad43/scripts/sessions#L73,L81

Let me know if the problem persists.
