### ISSUE TITLE
Request layout argument

### ISSUE THREAD

**Issue by theherk** [mostafaqanbaryan/zellij-attach-plugin#3]
Would be excellent to add the new `--new-session-with-layout` argument. I am starting with this script:

```fish
#!/usr/bin/env fish

function p # Get git project directory from .projects. See alias repocache.
    set REPO (zoxide query -l | rg --color=never -FxNf ~/.projects | sed s:"$HOME":~: | fzf --reverse)
    if test -n "$REPO"
        string replace '~' $HOME $REPO
    end
end

set -l pdir (p)
if test -z "$pdir"
    exit 1
end

set -l pname (basename $pdir)

if set -q ZELLIJ_SESSION_NAME
    if not string match -q "$pname" "$ZELLIJ_SESSION_NAME"
        zellij pipe --plugin file:~/bin/zellij-switch.wasm -- "$pname::$pdir"
    end
else
    cd $pdir
    if contains $pname (zellij list-sessions -ns)
        if contains $pname (zellij list-sessions -n | rg EXITED | cut -d' ' -f1 | cut -d':' -f2)
            zellij delete-session $pname
            zellij -n editor -s $pname
        else
            zellij attach $pname
        end
    else
        zellij -n editor -s $pname
    end
end
```

And I'd really love to do: `zellij pipe --plugin file:~/bin/zellij-switch.wasm -- -n editor "$pname::$pdir"`

**Comment by theherk** [comment]
I tried building with `let layout_name = "editor";` on [L21](https://github.com/mostafaqanbaryan/zellij-switch/blob/master/src/main.rs#L21), but it didn't work as expected. I was hoping to add another optional suffix, so it could be invoked with `"$name::$cwd::$layout"`.

I'll poke around at it some more. Let me know if you have some wisdom here.

---

To clarify, it still just launched with the default layout, rather than with layout `editor`.

**Comment by mostafaqanbaryan** [comment]
Resolved in https://github.com/mostafaqanbaryan/zellij-switch/pull/5 by @theherk.
